// <auto-generated />
namespace Winter2022_PassionProject_N01519420.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class actortable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actortable));
        
        string IMigrationMetadata.Id
        {
            get { return "202201202153520_actortable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
